# Gradle
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Game and loader
loom.platform=forge
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
forge_version=1.20.1-47.2.19
ffapi_version=0.92.6+1.11.15+1.20.1
fabric_loader_version=0.15.11

# Mod
maven_group=com.cleannrooster
archives_base_name=dungeons_iso
mod_version=3.6.1-1.20.1-another

# Optional compatibility dependencies
yacl_version=3.6.5+1.20.1-forge
cloth_config_version=11.1.106
player_anim_version=1.0.2+1.19.4
owo_version=0.11.2+1.20
mixinextras_version=0.4.1
spell_engine_version=0.15.12+1.20.1
spell_power_version=0.12.0+1.20.1
tiny_config_version=2.3.2
